---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv01
spec:
  storageClassName: kubernetes-operator
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: adc00qxg
    path: /scratch/k8s/volume01
---
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc01
spec:
  storageClassName: kubernetes-operator
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
---